if(DEFINED MODELICA_UTILITIES_INCLUDE)
  if(NOT MODELICA_UTILITIES_INCLUDE STREQUAL "")
    include_directories(${MODELICA_UTILITIES_INCLUDE})
  else()
    message(FATAL_ERROR "MODELICA_UTILITIES_INCLUDE is an empty string.")
  endif()
else()
  set(MODELICA_UTILITIES_INCLUDE "" CACHE PATH "Include directory of the (tool-vendor specific) ModelicaUtilities.h header file")
  if(NOT MODELICA_UTILITIES_INCLUDE STREQUAL "")
    include_directories(${MODELICA_UTILITIES_INCLUDE})
  else()
    message(FATAL_ERROR "MODELICA_UTILITIES_INCLUDE is an empty string.")
  endif()
endif()
